<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>$sitetitle$ - $pagetitle$</title>
    <link rel="stylesheet" type="text/css" media="screen"
          href="$root$css/main.css"/>
    <link rel="stylesheet" type="text/css" media="screen"
          href="$root$css/rust.css"/>
  </head>
  <body>
    <nav id="sidemenu">
      $nav$
    </nav>

    <div id="content">

      <h1 class="title">$pagetitle$</h1>

      <main>
        $contents$
      </main>

    </div>
  </body>
</html>
