#!/bin/sh

mkdir -p $HOME/.cabal/extra-dist

rm -rf libxslt
git clone --depth=1 https://github.com/GNOME/libxslt
cd libxslt

git rev-parse HEAD > new-hash
if diff new-hash $HOME/.cabal/extra-dist/libxslt.hash; then
  rm new-hash
  exit
fi

echo "Hashes differ => rebuilding"
mv new-hash $HOME/.cabal/extra-dist/libxslt.hash
sh autogen.sh
./configure --prefix=$HOME/.cabal/extra-dist
make install
